
spring.datasource.url=jdbc:postgresql://localhost:5432/ideias_midias_db
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.flyway.enabled=false

app.jwt.secret=LrraTlNcH94eDvDlL0hq9Sh8Atuzbnv4vO9UbrQoUzKif8HkcyMvGKP1i3TYUUlLFbhVSnNtM5GHSkerrSDa+A==

app.bootstrap.admin.enabled=false

spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=false

logging.level.org.flywaydb=OFF