spring.datasource.url=${STAGING_DB_URL}
spring.datasource.username=${STAGING_DB_USERNAME}
spring.datasource.password=${STAGING_DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

spring.flyway.enabled=false

app.jwt.secret=${APP_JWT_SECRET}

app.bootstrap.admin.enabled=false

spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=false