

CREATE TABLE public.admin_users (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    email character varying(255) NOT NULL,
    full_name character varying(150) NOT NULL,
    is_active boolean NOT NULL,
    last_login_at timestamp(6) without time zone,
    password_hash text NOT NULL,
    role character varying(50) NOT NULL,
    CONSTRAINT admin_users_role_check CHECK (((role)::text = ANY ((ARRAY['SUPER_ADMIN'::character varying, 'ADMIN'::character varying])::text[])))
);


--
-- TOC entry 219 (class 1259 OID 22742)
-- Name: admin_users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.admin_users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.admin_users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 22760)
-- Name: contact_methods; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.contact_methods (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    is_active boolean NOT NULL,
    sort_order integer NOT NULL,
    icon_name character varying(100),
    label_en character varying(150),
    label_pt character varying(150),
    type character varying(50) NOT NULL,
    value character varying(500) NOT NULL,
    CONSTRAINT contact_methods_type_check CHECK (((type)::text = ANY ((ARRAY['PHONE'::character varying, 'WHATSAPP'::character varying, 'EMAIL'::character varying, 'SOCIAL'::character varying])::text[])))
);


--
-- TOC entry 221 (class 1259 OID 22759)
-- Name: contact_methods_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.contact_methods ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contact_methods_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 22776)
-- Name: home_cards; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.home_cards (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    is_active boolean NOT NULL,
    sort_order integer NOT NULL,
    icon_name character varying(100),
    image_url text,
    short_description_en text,
    short_description_pt text,
    title_en character varying(255) NOT NULL,
    title_pt character varying(255) NOT NULL,
    section_id bigint NOT NULL
);


--
-- TOC entry 223 (class 1259 OID 22775)
-- Name: home_cards_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.home_cards ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.home_cards_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 22792)
-- Name: media_library; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.media_library (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    file_name character varying(255) NOT NULL,
    file_size bigint,
    file_type character varying(50) NOT NULL,
    file_url text NOT NULL,
    mime_type character varying(150),
    original_name character varying(255) NOT NULL,
    uploaded_by bigint,
    CONSTRAINT media_library_file_type_check CHECK (((file_type)::text = ANY ((ARRAY['IMAGE'::character varying, 'VIDEO'::character varying])::text[])))
);


--
-- TOC entry 225 (class 1259 OID 22791)
-- Name: media_library_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.media_library ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.media_library_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 22808)
-- Name: portfolio_project_media; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.portfolio_project_media (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    is_active boolean NOT NULL,
    sort_order integer NOT NULL,
    alt_text_en character varying(255),
    alt_text_pt character varying(255),
    media_type character varying(50) NOT NULL,
    media_url text NOT NULL,
    thumbnail_url text,
    project_id bigint NOT NULL,
    CONSTRAINT portfolio_project_media_media_type_check CHECK (((media_type)::text = ANY ((ARRAY['IMAGE'::character varying, 'VIDEO'::character varying])::text[])))
);


--
-- TOC entry 227 (class 1259 OID 22807)
-- Name: portfolio_project_media_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.portfolio_project_media ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.portfolio_project_media_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 22825)
-- Name: portfolio_projects; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.portfolio_projects (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    is_active boolean NOT NULL,
    sort_order integer NOT NULL,
    attributes_json text,
    client_name character varying(255),
    cover_image_url text,
    full_description_en text,
    full_description_pt text,
    is_featured boolean NOT NULL,
    location_en character varying(255),
    location_pt character varying(255),
    project_date date,
    short_description_en text,
    short_description_pt text,
    title_en character varying(255) NOT NULL,
    title_pt character varying(255) NOT NULL,
    video_url text,
    section_id bigint NOT NULL
);


--
-- TOC entry 229 (class 1259 OID 22824)
-- Name: portfolio_projects_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.portfolio_projects ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.portfolio_projects_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 232 (class 1259 OID 22842)
-- Name: section_attribute_definitions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.section_attribute_definitions (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    is_active boolean NOT NULL,
    sort_order integer NOT NULL,
    code character varying(120) NOT NULL,
    field_type character varying(30) NOT NULL,
    is_displayed_in_card boolean NOT NULL,
    is_displayed_in_details boolean NOT NULL,
    is_filterable boolean NOT NULL,
    is_required boolean NOT NULL,
    label_en character varying(255) NOT NULL,
    label_pt character varying(255) NOT NULL,
    options_json text,
    section_id bigint NOT NULL,
    CONSTRAINT section_attribute_definitions_field_type_check CHECK (((field_type)::text = ANY ((ARRAY['TEXT'::character varying, 'NUMBER'::character varying, 'DATE'::character varying, 'BOOLEAN'::character varying, 'SELECT'::character varying, 'MULTILINE'::character varying])::text[])))
);


--
-- TOC entry 231 (class 1259 OID 22841)
-- Name: section_attribute_definitions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.section_attribute_definitions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.section_attribute_definitions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 234 (class 1259 OID 22865)
-- Name: section_categories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.section_categories (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    is_active boolean NOT NULL,
    sort_order integer NOT NULL,
    description_en text,
    description_pt text,
    image_url text,
    name_en character varying(255) NOT NULL,
    name_pt character varying(255) NOT NULL,
    section_id bigint NOT NULL
);


--
-- TOC entry 233 (class 1259 OID 22864)
-- Name: section_categories_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.section_categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.section_categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 236 (class 1259 OID 22881)
-- Name: section_content_blocks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.section_content_blocks (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    is_active boolean NOT NULL,
    sort_order integer NOT NULL,
    block_type character varying(50) NOT NULL,
    content_en text,
    content_pt text,
    image_url text,
    subtitle_en character varying(255),
    subtitle_pt character varying(255),
    title_en character varying(255),
    title_pt character varying(255),
    video_url text,
    section_id bigint NOT NULL,
    CONSTRAINT section_content_blocks_block_type_check CHECK (((block_type)::text = ANY ((ARRAY['TEXT'::character varying, 'IMAGE'::character varying, 'VIDEO'::character varying, 'TEXT_IMAGE'::character varying, 'GALLERY'::character varying])::text[])))
);


--
-- TOC entry 235 (class 1259 OID 22880)
-- Name: section_content_blocks_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.section_content_blocks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.section_content_blocks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 238 (class 1259 OID 22897)
-- Name: section_item_attribute_values; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.section_item_attribute_values (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    value_boolean boolean,
    value_date date,
    value_number double precision,
    value_text text,
    attribute_definition_id bigint NOT NULL,
    section_item_id bigint NOT NULL
);


--
-- TOC entry 237 (class 1259 OID 22896)
-- Name: section_item_attribute_values_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.section_item_attribute_values ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.section_item_attribute_values_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 240 (class 1259 OID 22910)
-- Name: section_item_media; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.section_item_media (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    is_active boolean NOT NULL,
    sort_order integer NOT NULL,
    alt_text_en character varying(255),
    alt_text_pt character varying(255),
    media_type character varying(50) NOT NULL,
    media_url text NOT NULL,
    thumbnail_url text,
    item_id bigint NOT NULL,
    CONSTRAINT section_item_media_media_type_check CHECK (((media_type)::text = ANY ((ARRAY['IMAGE'::character varying, 'VIDEO'::character varying])::text[])))
);


--
-- TOC entry 239 (class 1259 OID 22909)
-- Name: section_item_media_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.section_item_media ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.section_item_media_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 242 (class 1259 OID 22927)
-- Name: section_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.section_items (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    is_active boolean NOT NULL,
    sort_order integer NOT NULL,
    attributes_json text,
    cover_image_url text,
    full_description_en text,
    full_description_pt text,
    is_featured boolean NOT NULL,
    item_type character varying(120),
    short_description_en text,
    short_description_pt text,
    specifications_en text,
    specifications_pt text,
    title_en character varying(255) NOT NULL,
    title_pt character varying(255) NOT NULL,
    video_url text,
    category_id bigint,
    section_id bigint NOT NULL
);


--
-- TOC entry 241 (class 1259 OID 22926)
-- Name: section_items_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.section_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.section_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 244 (class 1259 OID 22944)
-- Name: sections; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sections (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    is_active boolean NOT NULL,
    sort_order integer NOT NULL,
    allow_custom_attributes boolean NOT NULL,
    cover_image_url text,
    cover_video_url text,
    description_en text,
    description_pt text,
    details_view_mode character varying(100),
    display_variant character varying(100),
    layout_style character varying(100),
    name_en character varying(255) NOT NULL,
    name_pt character varying(255) NOT NULL,
    section_type character varying(50) NOT NULL,
    settings_json text,
    show_filters boolean NOT NULL,
    show_gallery boolean NOT NULL,
    show_intro boolean NOT NULL,
    show_item_details boolean NOT NULL,
    slug character varying(180) NOT NULL,
    CONSTRAINT sections_section_type_check CHECK (((section_type)::text = ANY ((ARRAY['CONTENT'::character varying, 'CATEGORY_ITEMS'::character varying, 'DIRECT_ITEMS'::character varying, 'PORTFOLIO'::character varying])::text[])))
);


--
-- TOC entry 243 (class 1259 OID 22943)
-- Name: sections_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.sections ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sections_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 246 (class 1259 OID 22967)
-- Name: site_settings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.site_settings (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    address_en text,
    address_pt text,
    company_name_en character varying(255) NOT NULL,
    company_name_pt character varying(255) NOT NULL,
    company_video_url text,
    hero_background_type character varying(50) NOT NULL,
    hero_background_url text,
    hero_subtitle_en text,
    hero_subtitle_pt text,
    hero_title_en character varying(255),
    hero_title_pt character varying(255),
    location_lat numeric(10,7),
    location_lng numeric(10,7),
    logo_url text,
    map_embed_url text,
    short_intro_en text,
    short_intro_pt text,
    CONSTRAINT site_settings_hero_background_type_check CHECK (((hero_background_type)::text = ANY ((ARRAY['IMAGE'::character varying, 'VIDEO'::character varying, 'COLOR'::character varying])::text[])))
);


--
-- TOC entry 245 (class 1259 OID 22966)
-- Name: site_settings_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.site_settings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.site_settings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 248 (class 1259 OID 22982)
-- Name: theme_settings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.theme_settings (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    accent_color character varying(20) NOT NULL,
    background_color character varying(20) NOT NULL,
    hero_overlay_color character varying(20) NOT NULL,
    primary_color character varying(20) NOT NULL,
    secondary_color character varying(20) NOT NULL,
    text_color character varying(20) NOT NULL
);


--
-- TOC entry 247 (class 1259 OID 22981)
-- Name: theme_settings_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.theme_settings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.theme_settings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4936 (class 2606 OID 22758)
-- Name: admin_users admin_users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admin_users
    ADD CONSTRAINT admin_users_pkey PRIMARY KEY (id);


--
-- TOC entry 4940 (class 2606 OID 22774)
-- Name: contact_methods contact_methods_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contact_methods
    ADD CONSTRAINT contact_methods_pkey PRIMARY KEY (id);


--
-- TOC entry 4942 (class 2606 OID 22790)
-- Name: home_cards home_cards_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.home_cards
    ADD CONSTRAINT home_cards_pkey PRIMARY KEY (id);


--
-- TOC entry 4944 (class 2606 OID 22806)
-- Name: media_library media_library_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.media_library
    ADD CONSTRAINT media_library_pkey PRIMARY KEY (id);


--
-- TOC entry 4946 (class 2606 OID 22823)
-- Name: portfolio_project_media portfolio_project_media_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.portfolio_project_media
    ADD CONSTRAINT portfolio_project_media_pkey PRIMARY KEY (id);


--
-- TOC entry 4948 (class 2606 OID 22840)
-- Name: portfolio_projects portfolio_projects_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.portfolio_projects
    ADD CONSTRAINT portfolio_projects_pkey PRIMARY KEY (id);


--
-- TOC entry 4950 (class 2606 OID 22863)
-- Name: section_attribute_definitions section_attribute_definitions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.section_attribute_definitions
    ADD CONSTRAINT section_attribute_definitions_pkey PRIMARY KEY (id);


--
-- TOC entry 4952 (class 2606 OID 22879)
-- Name: section_categories section_categories_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.section_categories
    ADD CONSTRAINT section_categories_pkey PRIMARY KEY (id);


--
-- TOC entry 4954 (class 2606 OID 22895)
-- Name: section_content_blocks section_content_blocks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.section_content_blocks
    ADD CONSTRAINT section_content_blocks_pkey PRIMARY KEY (id);


--
-- TOC entry 4956 (class 2606 OID 22908)
-- Name: section_item_attribute_values section_item_attribute_values_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.section_item_attribute_values
    ADD CONSTRAINT section_item_attribute_values_pkey PRIMARY KEY (id);


--
-- TOC entry 4958 (class 2606 OID 22925)
-- Name: section_item_media section_item_media_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.section_item_media
    ADD CONSTRAINT section_item_media_pkey PRIMARY KEY (id);


--
-- TOC entry 4960 (class 2606 OID 22942)
-- Name: section_items section_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.section_items
    ADD CONSTRAINT section_items_pkey PRIMARY KEY (id);


--
-- TOC entry 4962 (class 2606 OID 22965)
-- Name: sections sections_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sections
    ADD CONSTRAINT sections_pkey PRIMARY KEY (id);


--
-- TOC entry 4966 (class 2606 OID 22980)
-- Name: site_settings site_settings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.site_settings
    ADD CONSTRAINT site_settings_pkey PRIMARY KEY (id);


--
-- TOC entry 4968 (class 2606 OID 22995)
-- Name: theme_settings theme_settings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.theme_settings
    ADD CONSTRAINT theme_settings_pkey PRIMARY KEY (id);


--
-- TOC entry 4964 (class 2606 OID 22999)
-- Name: sections ukciuesjom3u8tjutjm6ym4go4k; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sections
    ADD CONSTRAINT ukciuesjom3u8tjutjm6ym4go4k UNIQUE (slug);


--
-- TOC entry 4938 (class 2606 OID 22997)
-- Name: admin_users ukcp8822350s9vtyww7xdbgeuvu; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admin_users
    ADD CONSTRAINT ukcp8822350s9vtyww7xdbgeuvu UNIQUE (email);


--
-- TOC entry 4979 (class 2606 OID 23050)
-- Name: section_items fk2miujrmqvwyvd8c0hsleoy7w7; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.section_items
    ADD CONSTRAINT fk2miujrmqvwyvd8c0hsleoy7w7 FOREIGN KEY (category_id) REFERENCES public.section_categories(id);


--
-- TOC entry 4972 (class 2606 OID 23015)
-- Name: portfolio_projects fk3reiaey89tsj3b9pu0jrw0m7l; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.portfolio_projects
    ADD CONSTRAINT fk3reiaey89tsj3b9pu0jrw0m7l FOREIGN KEY (section_id) REFERENCES public.sections(id);


--
-- TOC entry 4976 (class 2606 OID 23040)
-- Name: section_item_attribute_values fk5bactiqkmolksb4ekv8vamki7; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.section_item_attribute_values
    ADD CONSTRAINT fk5bactiqkmolksb4ekv8vamki7 FOREIGN KEY (section_item_id) REFERENCES public.section_items(id);


--
-- TOC entry 4970 (class 2606 OID 23005)
-- Name: media_library fk95kwum1s8henvp64r1nlm4kwc; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.media_library
    ADD CONSTRAINT fk95kwum1s8henvp64r1nlm4kwc FOREIGN KEY (uploaded_by) REFERENCES public.admin_users(id);


--
-- TOC entry 4973 (class 2606 OID 23020)
-- Name: section_attribute_definitions fkboj53m6013wb7i2286cqn337; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.section_attribute_definitions
    ADD CONSTRAINT fkboj53m6013wb7i2286cqn337 FOREIGN KEY (section_id) REFERENCES public.sections(id);


--
-- TOC entry 4975 (class 2606 OID 23030)
-- Name: section_content_blocks fkerx7stf8ala6bc6qqsvat6s33; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.section_content_blocks
    ADD CONSTRAINT fkerx7stf8ala6bc6qqsvat6s33 FOREIGN KEY (section_id) REFERENCES public.sections(id);


--
-- TOC entry 4978 (class 2606 OID 23045)
-- Name: section_item_media fkexqoapmxptqm60hqgbnpt36wq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.section_item_media
    ADD CONSTRAINT fkexqoapmxptqm60hqgbnpt36wq FOREIGN KEY (item_id) REFERENCES public.section_items(id);


--
-- TOC entry 4969 (class 2606 OID 23000)
-- Name: home_cards fkiayao56lqq67o4dxf869av185; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.home_cards
    ADD CONSTRAINT fkiayao56lqq67o4dxf869av185 FOREIGN KEY (section_id) REFERENCES public.sections(id);


--
-- TOC entry 4977 (class 2606 OID 23035)
-- Name: section_item_attribute_values fklrbbwm5jtnrko0ho3stn4jy9g; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.section_item_attribute_values
    ADD CONSTRAINT fklrbbwm5jtnrko0ho3stn4jy9g FOREIGN KEY (attribute_definition_id) REFERENCES public.section_attribute_definitions(id);


--
-- TOC entry 4980 (class 2606 OID 23055)
-- Name: section_items fkm7wwvo7nj7h2ldw19trlgbyvs; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.section_items
    ADD CONSTRAINT fkm7wwvo7nj7h2ldw19trlgbyvs FOREIGN KEY (section_id) REFERENCES public.sections(id);


--
-- TOC entry 4971 (class 2606 OID 23010)
-- Name: portfolio_project_media fkojycyiqo3fxm6lilayv5x29b8; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.portfolio_project_media
    ADD CONSTRAINT fkojycyiqo3fxm6lilayv5x29b8 FOREIGN KEY (project_id) REFERENCES public.portfolio_projects(id);


--
-- TOC entry 4974 (class 2606 OID 23025)
-- Name: section_categories fksq2usuwqw82mtus5kfdxpnf0r; Type: FK CONSTRAINT; Schema: public; Owner: -
--
--

ALTER TABLE ONLY public.section_categories
    ADD CONSTRAINT fksq2usuwqw82mtus5kfdxpnf0r FOREIGN KEY (section_id) REFERENCES public.sections(id);

