CREATE TABLE public.admin_refresh_tokens (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    token text NOT NULL,
    expires_at timestamp(6) without time zone NOT NULL,
    revoked_at timestamp(6) without time zone,
    last_used_at timestamp(6) without time zone,
    is_revoked boolean NOT NULL DEFAULT false,
    admin_user_id bigint NOT NULL,
    CONSTRAINT uk_admin_refresh_tokens_token UNIQUE (token),
    CONSTRAINT fk_admin_refresh_tokens_admin_user
        FOREIGN KEY (admin_user_id)
        REFERENCES public.admin_users(id)
        ON DELETE CASCADE
);

CREATE INDEX idx_admin_refresh_tokens_admin_user
    ON public.admin_refresh_tokens(admin_user_id);

CREATE INDEX idx_admin_refresh_tokens_expires_at
    ON public.admin_refresh_tokens(expires_at);