CREATE TABLE public.admin_audit_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id bigint,
    email varchar(255),
    action varchar(80) NOT NULL,
    success boolean NOT NULL,
    ip_address varchar(80),
    user_agent text,
    message text,
    created_at timestamp(6) without time zone NOT NULL
);

CREATE INDEX idx_admin_audit_logs_admin_id
    ON public.admin_audit_logs(admin_id);

CREATE INDEX idx_admin_audit_logs_action
    ON public.admin_audit_logs(action);

CREATE INDEX idx_admin_audit_logs_created_at
    ON public.admin_audit_logs(created_at);