CREATE TABLE page_views (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    path          VARCHAR(255) NOT NULL,
    section_slug  VARCHAR(180),
    visitor_hash  VARCHAR(64) NOT NULL,
    viewed_at     TIMESTAMP NOT NULL
);

CREATE INDEX idx_page_views_viewed_at ON page_views (viewed_at);
CREATE INDEX idx_page_views_section_slug ON page_views (section_slug);
